[development]
address      = "localhost"
port         = 80
keep_alive   = 5
log          = "normal"
template_dir = "src/templates/"
assets_dir   = "src/assets/"
limits       = { forms = 32768 }

[staging]
address      = "0.0.0.0"
port         = 80
keep_alive   = 5
log          = "normal"
template_dir = "src/templates/"
assets_dir   = "src/assets/"
limits       = { forms = 32768 }

[production]
address      = "0.0.0.0"
port         = 80
keep_alive   = 5
log          = "critical"
template_dir = "src/templates/"
assets_dir   = "src/assets/"
limits       = { forms = 32768 }
